### ISSUE TITLE
Remove login and password recovery tabs for MFIN staff

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#28]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5007668210

---

[Related base-build theme issue](https://github.com/bcgov/bcbb-theme/issues/15)

## Users logging in with IDIR

Most people will be authenticating on the site using their IDIR accounts. Currently, there are tabs at `/user/login` for login and resetting passwords. These options are not useful to people logging in with IDIR and should be removed. If people need to reset passwords, they change their Microsoft credentials, not Drupal. The change password option is misleading. 

The page is called Login, the tab is called Login and the CTA on the link is titled Login. The tab is redundant and should be removed.

![image](https://github.com/bcgov/bcbb/assets/3910508/fac590e5-a609-4418-b235-9c8168b9fcea)

## Drupal users

Administrators will continue to login using Drupal accounts at `/user/login?showcore`. For these users, the tabs should remain as they are.

>**NOTE**: If it proves difficult to manage tabs on the same URL, not showing the tabs takes priority over showing them. Admins have other ways to recover passwords if needed.

## DoD

- [x] at `/user/login`, I see no login or password tab
- [x] at `/user/login?showcore` I see typical Drupal login tabs

**Comment by CraigClark** [comment]
@NicoledeGreef while we are at this, we can change the label on the CTA link. Right now it says *Log in with keycloak*. I recommend changing that to whatever people in MFIN typically call their login method. "log in with your Gov BC credentials', 'Log in with Office 365', something that makes it obvious to staff that they already have an account to access site features with.

**Comment by NicoledeGreef** [comment]
I have noticed some different labels when accessing services hosted in Openshift and have wondered why there hasn't been a more standardized approach in order to provide a more consistent experience across web apps.  Some indicate "keycloak" which means nothing to users, IMO.  This is outside of our scope but we can choose something that is meaningful and consistent for our end users to be included in the bcbb and implemented in MFIN-D-C and other new apps.

Something as simple as "Login" or "BC Gov Login" is generic and gets the point across to me, however,  I'll defer to the Digital Services team for recommendations. @victoriazou @chrislaick please loop in others as needed

**Comment by NicoledeGreef** [comment]
I could not apply a label of "base-build candidate" to this ticket as it is already in the bcbb product repo. We should discuss this one at the next "BC Base Build Discussions" meeting.

**Comment by CraigClark** [comment]
This has been done
